### ISSUE TITLE
Show the tissue browser in the right drawer.

### ISSUE THREAD

**Issue by adphillips2017** [hubmapconsortium/ccf-ui#168] opened 2020-03-17 15:34 UTC
Issue #132 

On the right to show the Tissue Browser (aka results) and nav that contains icons for getting to filters and other options

**Comment by bherr2** [comment] 2020-04-20 14:55
Duplicate of user stories marked as label:Tissue Browser

**Closed by bherr2** 2020-04-20 14:55 UTC
Labels: Tissue Browser, duplicate, user-story
